// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// contourWalker
NumericMatrix contourWalker(IntegerMatrix& dm, NumericMatrix& xyz, NumericVector& levels, double maximumPertubation);
RcppExport SEXP contoureR_contourWalker(SEXP dmSEXP, SEXP xyzSEXP, SEXP levelsSEXP, SEXP maximumPertubationSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type xyz(xyzSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type levels(levelsSEXP);
    Rcpp::traits::input_parameter< double >::type maximumPertubation(maximumPertubationSEXP);
    __result = Rcpp::wrap(contourWalker(dm, xyz, levels, maximumPertubation));
    return __result;
END_RCPP
}
