# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

contourWalker <- function(dm, xyz, levels, maximumPertubation = 1e-5) {
    .Call('contoureR_contourWalker', PACKAGE = 'contoureR', dm, xyz, levels, maximumPertubation)
}

